[versions]
agp = "9.0.0"
appcompatVersion = "1.7.0"
gson = "2.13.2"
gsonVersion = "2.11.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
materialVersion = "1.12.0"
volley = "1.2.1"

[libraries]
appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-v2110 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

